---
- hosts: all
  gather_facts: no
  tasks:
    - name: create a cloudformation stack
      cloudformation:
        stack_name: "{{ stack_name }}"
        state: "present"
        region: "{{ region }}"
        disable_rollback: true
        template: "/home/ansible/cloudformation/templates/{{ enviornment }}/{{ service }}/{{ service }}.json"
        template_parameters:
          KeyName: "{{ KeyName }}"
          InstanceType: "{{ InstanceType }}"
          ImageId: "{{ ImageId }}"
        tags:
          Stack: "{{ stack_tag }}"
