- hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ vars_files }}"
  tasks:
    - name: "Remove each EC2 instance from the ELB"
      ec2_elb:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        ec2_elbs: "{{ item.elb }}"
        region: "{{ ec2_elb.region }}"
        instance_id: "{{ item.instance }}"
      with_items: "{{ loadbalancers }}"
      ignore_errors: true
      #  - { elb: 'elb1', instances: 'instance1', 'instance2' }
      #  - { elb: 'elb2', instances: 'instance1', 'instance2' }
    - name: Get instances info
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Stack: "{{ stack.tag }}"
      register: ec2_facts
    - debug:
        var: ec2_facts
 
    - name: Create the snapshot on secondray volume of each ec2 instance
      ec2_snapshot:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: "{{ item.instance_id }}"
        device_name: "{{ ec2_sanpshot.device_name }}"
        description: "snapshot of {{ item.tags.Name }}"
        snapshot_tags:
          Name: "{{ item.tags.Name }}"
      with_items: "{{ ec2_facts.instances }}"


