- hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ vars_files }}"
  tasks:
    - name: Get instances info
      ec2_instance_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Stack: "{{ stack.tag }}"
      register: ec2_facts
    - debug:
        msg: "{{ ec2_facts | json_query('instances[*].{instance: instance_id, Name: tags.Name}') }}"

    - name: "Remove each EC2 instance from the ELB"
      ec2_elb:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: absent
        ec2_elbs: "{{ ec2_elb.elb }}"
        region: "{{ ec2_elb.region }}"
        instance_id: "{{ item.instance_id }}"
      with_items: "{{ ec2_facts.instances }}"
