---
- hosts: all
  gather_facts: no
  vars_files:
    - "{{ vars_files }}"
  tasks:
    - name: Create a cloudformation stack
      cloudformation:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        stack_name: "{{ stack.name }}"
        state: "present"
        region: "{{ stack.region }}"
        #disable_rollback: true
        termination_protection: no
        template: "/home/ansible/cloudformation/templates/{{ enviornment }}/{{ service }}/{{ service }}.json"
        template_parameters:
          KeyName: "{{ template.KeyName }}"
          InstanceType: "{{ template.InstanceType }}"
          ImageId: "{{ template.ImageId }}"
          #SnapshotId: "{{ template.SnapshotId }}"
         # SnapshotId2: "{{ template.SnapshotId2 }}"
        #with_items: "{{ SnapshotId }"
        tags:
          Stack: "{{ stack.tag }}"
      #with_items: "{{ SnapshotIds }}"
