- hosts: localhost
  gather_facts: no
  vars_files:
    - "{{ vars_files }}"
  tasks:
    - name: Gather snapshot facts
      ec2_snapshot_info:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          tag:Name: "{{ ec2_snapshot.tag }}_{{ ec2_snapshot.patch_cycle }}"
      register: ec2_snapshot
    - debug:
        var: ec2_snapshot

    - name: Registering snapshots ids
      set_fact:
        snapshot_map: "{{ ec2_snapshot | json_query('snapshots[*].{Snapshot: snapshot_id, Name: tags.Name}') }}"
        cacheable: yes
      register: snapshot_map
    - debug:
        var: snapshot_map

    - name: Create file with snapshot details
      copy:
        content: "{{ snapshot_map }}"
        dest: "/tmp/my_file"

